# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Start time for the notifications')),
                ('end_time', models.TimeField(verbose_name='End time for the notifications')),
                ('range', models.IntegerField(verbose_name='The time of appearance of new words / min.')),
                ('last_request', models.TimeField(blank=True)),
                ('number_word', models.IntegerField(default=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Word')),
                ('description', models.TextField(max_length=2000, verbose_name='Description')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
        ),
    ]
