# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-12 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_words', '0002_auto_20161012_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='name',
            new_name='word',
        ),
    ]
