# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-12 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_words', '0003_auto_20161012_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='name',
        ),
    ]
