# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 15:24
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('english_words', '0004_auto_20161012_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='last_request',
            field=models.DateTimeField(blank=True,
                                       default=datetime.datetime(2016, 11, 22, 15, 24, 3, 802858, tzinfo=utc),
                                       verbose_name='Last request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='last_request',
            field=models.TimeField(blank=True, verbose_name='Last request'),
        ),
    ]
