# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_words', '0005_auto_20161122_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='description',
        ),
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.TextField(default=' ', max_length=1000, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='transcription',
            field=models.CharField(default=' ', max_length=128, verbose_name='Word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.TextField(default=' ', max_length=1000, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
