# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-14 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('english_words', '0006_auto_20161222_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 14, 15, 5, 40, 910675, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Example'),
        ),
        migrations.AlterField(
            model_name='word',
            name='last_request',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last request'),
        ),
        migrations.AlterField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, max_length=128, verbose_name='Transcription'),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.TextField(max_length=1000, verbose_name='Translation'),
        ),
    ]
