# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-15 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_words', '0008_auto_20170114_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='last_request',
            field=models.DateTimeField(blank=True, default='1901-01-01', verbose_name='Last request'),
        ),
    ]
