# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-17 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_words', '0010_auto_20180317_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
    ]
