# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-11 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(verbose_name='The date of event')),
                ('start', models.TimeField(verbose_name='The time of event')),
                ('end', models.TimeField(verbose_name='The expiry time of event')),
                ('time_notice', models.TimeField(verbose_name='Time of notification')),
                ('date_notice', models.DateField(verbose_name='Date of notification')),
                ('repeat', models.CharField(choices=[('never', 'never'), ('1day', '1 day'), ('2day', '2 days'), ('1wk', '1 week'), ('2wks', '2 weeks'), ('mn', 'month'), ('yr', 'year')], default='never', max_length=10, verbose_name='The retry time of the event')),
                ('last_request', models.DateField(blank=True, verbose_name='Last query time')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Color for this task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_user', to='user.UserProfile')),
            ],
        ),
    ]
