# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(verbose_name='The time of notification')),
                ('end_time', models.DateTimeField(verbose_name='The time expiration of notification')),
                ('warning_time', models.IntegerField(verbose_name='The time for warning before of notification')),
            ],
        ),
    ]
