# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0002_auto_20161017_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='only_notice',
            field=models.BooleanField(default=False, verbose_name='Notice'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of event'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_notice',
            field=models.DateField(blank=True, null=True, verbose_name='Date of notification'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='Expiry time of event'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='Time of event'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_notice',
            field=models.TimeField(blank=True, null=True, verbose_name='Time of notification'),
        ),
    ]
