# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160919_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.AddField(
            model_name='task',
            name='length',
            field=models.IntegerField(default=1, verbose_name='The amount of time for this task'),
            preserve_default=False,
        ),
    ]
