# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160922_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat',
            field=models.CharField(choices=[('never', 'never'), ('1day', '1 day'), ('2day', '2 day'), ('1wk', '1 week'), ('2wk', '2 week'), ('mn', 'month'), ('yr', 'year')], default='never', max_length=10, verbose_name='The retry time of the event'),
        ),
    ]
