# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_task_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 9, 26, 15, 23, 1, 101628, tzinfo=utc), verbose_name='The date of notification'),
            preserve_default=False,
        ),
    ]
