# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(verbose_name='The expiry time of notification'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(verbose_name='The time of notification'),
        ),
    ]
