# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160927_1518'),
        ('home', '0011_auto_20160926_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='warning_time',
        ),
        migrations.AddField(
            model_name='task',
            name='date_notice',
            field=models.DateField(default=datetime.date(2016, 10, 2), verbose_name='Date of notification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='end',
            field=models.TimeField(default=datetime.time(9, 40, 32, 604580), verbose_name='The expiry time of event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='last_request',
            field=models.DateField(blank=True, default=datetime.date(2016, 10, 2), verbose_name="It's the time of the last query to this task"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.TimeField(default=datetime.time(9, 40, 49, 180928), verbose_name='The time of event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='time_notice',
            field=models.TimeField(default=datetime.time(9, 40, 58, 606209), verbose_name='Time of notification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_user', to='user.UserProfile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(verbose_name='The date of event'),
        ),
    ]
