# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 17:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_auto_20161123_1844'),
        ('english_words', '0005_auto_20161122_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwaitingDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, max_length=1000, verbose_name="Recipient's token")),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Task')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='english_words.Word')),
            ],
        ),
    ]
