# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 13:01
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('push_message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awaitingdelivery',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True,
                                       default=datetime.datetime(2016, 10, 24, 13, 1, 16, 774861, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awaitingdelivery',
            name='token',
            field=models.CharField(blank=True, max_length=1000, verbose_name="Recipient's token"),
        ),
    ]
