# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 17:50
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('push_message', '0002_auto_20161024_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaitingdelivery',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
