# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 17:51
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('push_message', '0003_auto_20161123_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaitingdelivery',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
